const actionTypes = {
  START_APP: "START_APP",
  UPDATE_STATE_DATA: "UPDATE_STATE_DATA",
  UPDATE_REPORT_STATE_DATA: "UPDATE_REPORT_STATE_DATA",
  //Manage Tasks
  UPDATE_DATA: "UPDATE_DATA",
  DELETE_ITEM: "DELETE_ITEM",
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM"
};
export default actionTypes;
